//! Clipboard history persistence, backed by `airnest` (`SQLite`) with the
//! `#[persistent]` attribute macro from `airnest-macros`.
//!
//! The on-disk table holds one row per copied item. Each row's
//! `timestamp` is the same `u64` we already pass around as the entry id
//! — we use it as the equality-lookup index and the in-app identifier,
//! while `airnest`'s `UUIDv7` primary key (`id`) stays internal.

#![allow(clippy::too_many_arguments)] // `ClipboardRow::new` is generated by `#[persistent]`.

use std::path::{Path, PathBuf};
use std::sync::Arc;

use ::airnest::{Order, Store, persistent};
use bytes::Bytes;
use serde::{Deserialize, Serialize};

use crate::clipboard::models::{EntryKind, bytes_serde};

const MAX_ENTRIES: i64 = 1_000;

/// On-disk representation of a clipboard entry.
///
/// `#[persistent(index(hash_hex, timestamp))]` makes `hash_hex` (text, dedup
/// lookup) and `timestamp` (text-mirrored u64, equality lookup) into indexed
/// columns. The injected `id: AirId<Self>` (`UUIDv7`) is the SQL primary key.
#[persistent(index(hash_hex, timestamp))]
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClipboardRow {
    pub timestamp: u64,
    pub mime_type: String,
    pub kind: EntryKind,
    #[serde(with = "bytes_serde")]
    pub data: Bytes,
    #[serde(with = "bytes_serde")]
    pub thumb: Bytes,
    pub hash: [u8; 32],
    pub hash_hex: String,
    pub sensitive: bool,
    pub filename: Option<String>,
}

/// Async wrapper around an [`airnest::Store`] pinned to [`ClipboardRow`].
pub struct AirStore {
    inner: Store,
}

impl AirStore {
    /// Open (or create) the `SQLite` database at `path`. Returns an `Arc` so
    /// the watcher task and the daemon's connection handlers can share it.
    pub async fn open(path: &Path) -> Result<Arc<Self>, String> {
        let path_str = path.display().to_string();
        let inner = Store::open(&path_str)
            .await
            .map_err(|e| format!("opening {}: {e}", path.display()))?;
        Ok(Arc::new(Self { inner }))
    }

    /// Dedup by `hash_hex`, then save. Returns `Ok(true)` if a new row was
    /// stored, `Ok(false)` if a row with the same `hash_hex` already
    /// existed. After a successful save, trims the table to
    /// [`MAX_ENTRIES`].
    pub async fn insert(&self, row: &ClipboardRow) -> Result<bool, String> {
        let dup = ClipboardRow::find(&self.inner)
            .hash_hex(&row.hash_hex)
            .first()
            .await
            .map_err(|e| format!("dedup query: {e}"))?;
        if dup.is_some() {
            return Ok(false);
        }
        self.inner.save(row).await.map_err(|e| e.to_string())?;
        self.evict_if_needed().await?;
        Ok(true)
    }

    /// Look up by `timestamp` (the same value the rest of the app uses as
    /// the entry id).
    pub async fn get_by_id(&self, id: u64) -> Result<Option<ClipboardRow>, String> {
        ClipboardRow::find(&self.inner)
            .timestamp(&id)
            .first()
            .await
            .map_err(|e| e.to_string())
    }

    /// Recent-N entries ordered newest-first by `SQLite`'s auto `saved_at`.
    pub async fn get_recent(&self, limit: usize) -> Result<Vec<ClipboardRow>, String> {
        self.inner
            .find::<ClipboardRow>()
            .order_by("saved_at", Order::Desc)
            .limit(limit)
            .all()
            .await
            .map_err(|e| e.to_string())
    }

    /// Delete by `timestamp`. Looks up the row first, then deletes via its
    /// `airnest`-internal `UUIDv7` id.
    #[allow(dead_code)]
    pub async fn delete(&self, id: u64) -> Result<bool, String> {
        let Some(row) = self.get_by_id(id).await? else {
            return Ok(false);
        };
        self.inner.delete(&row).await.map_err(|e| e.to_string())?;
        Ok(true)
    }

    /// Total entry count.
    #[allow(dead_code)]
    pub async fn count(&self) -> Result<i64, String> {
        self.inner
            .count::<ClipboardRow>()
            .await
            .map_err(|e| e.to_string())
    }

    /// Drop oldest entries past [`MAX_ENTRIES`].
    ///
    /// Byte-size based eviction (formerly `MAX_BYTES`) is dropped because
    /// `airnest` doesn't expose per-row blob length cheaply; `SQLite` /
    /// `bitcode` blobs tend to stay well under 64 MB for typical clipboard
    /// payloads, so the count cap is the practical limit here.
    pub async fn evict_if_needed(&self) -> Result<(), String> {
        let total = self.count().await?;
        if total <= MAX_ENTRIES {
            return Ok(());
        }
        let surplus = (total - MAX_ENTRIES) as usize;
        let oldest = self
            .inner
            .find::<ClipboardRow>()
            .order_by("saved_at", Order::Asc)
            .limit(surplus)
            .all()
            .await
            .map_err(|e| e.to_string())?;
        for row in oldest {
            self.inner.delete(&row).await.map_err(|e| e.to_string())?;
        }
        Ok(())
    }
}

pub type SharedStore = Arc<AirStore>;

/// Default on-disk location: `XDG_DATA_HOME/luncher/history.sqlite`.
pub fn db_path() -> Result<PathBuf, String> {
    let base = dirs::data_dir().ok_or_else(|| "XDG_DATA_HOME not set".to_string())?;
    let path = base.join("luncher").join("history.sqlite");
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("creating {}: {e}", parent.display()))?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(parent, std::fs::Permissions::from_mode(0o700))
                .map_err(|e| format!("chmod {}: {e}", parent.display()))?;
        }
    }
    Ok(path)
}

/// Lowercase hex of an arbitrary byte slice, used to populate `hash_hex`.
pub fn hex_encode(bytes: &[u8]) -> String {
    const LUT: &[u8; 16] = b"0123456789abcdef";
    let mut s = String::with_capacity(bytes.len() * 2);
    for &b in bytes {
        s.push(LUT[(b >> 4) as usize] as char);
        s.push(LUT[(b & 0x0f) as usize] as char);
    }
    s
}
